### ISSUE TITLE
Run options

### ISSUE THREAD

**Issue by connormanning** [hobuinc/untwine#1]
Need to be able to run something like `untwine build -i input.laz -o output` - hiding the 2-phase implementation detail of this application.  Also some switches that are heavily used in Entwine.  I propose some options:

- `--input`: input files/directories, or potentially pointing at a `pretile` output from earlier if that step was done in isolation
- `--output`: ouput directory
- `--output-type`: `"laszip", "binary", "zstandard"` for the output data
- `--force`: if there is data in the output directory, ignore/override it - if there is already `ept.json` in the output we should error if `force` is not set
- `--scale`: set the output XYZ scale factor (should be inferred from data by default, but needs an explicit override as well), needs to support both a single value (e.g. `0.01`) and non-uniform scaling (e.g. `0.01 0.01 0.0025`)
- `--pretile`: directory for the pretile step - defaults to `<output-dir>/ept-pretile` so this doesn't need to be specified
- `--pretile-type`: probably for future addition - but would definitely want the ability to write the pretile data as LAZ/ZST or whatever compressed format
- `--pretile-delete`: automatically delete the pretile output after the build since it may be quite large
- `--threads`: total number of threads (could split this out into things like "io-threads" etc. if these ratios matter)
- `--bounds`: clip the output data to a certain XYZ bounds
- `--srs`: set the SRS in the output `ept.json`
- `--reprojection (in) [out]`: reproject data and use the output SRS as the `srs` in `ept.json`

**Comment by connormanning** [comment]
After a bit of discussion, might also want to consider:
- `--span`: set the EPT [span](https://entwine.io/entwine-point-tile.html#span)
- `--schema`: set the stored output attributes

**Comment by abellgithub** [comment]
This issue is stale.
