### ISSUE TITLE
Untwine on Windows creates corrupted COPC files when unicode path is used

### ISSUE THREAD

**Issue by wonder-sk** [hobuinc/untwine#120]
Thanks to the fixes introduced within #56 it is now possible to run untwine on windows with unicode paths. Untwine also generates output COPC file with unicode path, but it consistently produces broken COPC files - the file size of the output file is roughly half of the original LAZ file. Tested with multiple files, with the same results:
- `c.laz` always gets correctly indexed to `c.copc.laz`
- `č.laz` always gets broken result in `č.copc.laz`

Using untwine from osgeo4w, with pdal 2.3. Untwine is being started from qgis (couldn't test with command line due to #119)

It is worth noting that the file size of the broken output COPC file is not always the same, but it is always roughly half of the original file size.

![image](https://user-images.githubusercontent.com/193367/174302548-d06b8d91-0509-4891-b0a0-ca7c570a8613.png)

**Comment by hobu** [comment]
`wmain` branch updates windows to use wmain. Maybe this will take care of the unicode issue.
