### ISSUE TITLE
Untwine leaves behind temporary directory

### ISSUE THREAD

**Issue by wonder-sk** [hobuinc/untwine#122]
I run untwine from command line, e.g.:
```
untwine -i hello.laz -o hello.copc.laz -s
```
Once untwine finishes, it leaves behind `hello.copc.laz_tmp` directory with lots of data in it, and needs to be removed manually afterwards. It would be more appropriate to remove the temp directory on exit (and maybe leave it there only when there's a failure?)

**Comment by hobu** [comment]
commandline has ` --preserve_temp_dir` which is supposed to cause stuff to stick around. Maybe the behavior of this on your `qgis` branch isn't aligned with `main`

**Comment by uclaros** [comment]
This issue is valid in `main` also. It seems like `--preserve_temp_dir` is always enabled for both copc and ept output.
