### ISSUE TITLE
--file_limit option comment

### ISSUE THREAD

**Issue by GGuidiRontani** [hobuinc/untwine#127]
We noticed an unexpected behavior while using the --file_limit option for exploratories processes.
```
path\untwine --files=path\folder --output_dir=path\output.copc.laz --stats=true --single_file=true --file_limit=1
```
Our inputs are 1.4 laz tiles.  We work with Untwine compiled from master https://github.com/hobuinc/untwine/issues/125#issue-1300303888 and also Untwine available with OSGeo4W

On both compilations, the results are copc files with less points than from the original file used as sample. The input contain around 15 million points while the output holds exactly 5 million points.

This is not properly a blocking problem but it must be kept in mind for the control phase of the process before executing the final one.

**Comment by abellgithub** [comment]
`--file_limit` is a debugging option. I'm not sure what you're expecting, but that option (`--file_limit=1`) will limit input to a single file, regardless of the number of files in the source directory.

**Comment by GGuidiRontani** [comment]
We were using this option to validate our process before executing the same one (wihtout --file_limit) on the full dataset.

This observation was made during the the control phase but, like I said, this is not a blocknig problem. I mostly made it for the records. This issue can be closed I guess.

**Comment by abellgithub** [comment]
I don't see any code that would limit a point count based on the `file_limit` option. A code reference would be helpful.
