### ISSUE TITLE
Linking problem when compelling untwine from source.

### ISSUE THREAD

**Issue by zexhuang** [hobuinc/untwine#130]
Dear developers,

I encounter this issue when i build untwine from source, following the build instruction:

**_[  2%] Linking CXX executable untwine
/usr/bin/ld: /home/ubuntu/anaconda3/envs/budjbim2/lib/libpdal_base.so.14.2.0: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/untwine.dir/build.make:566: untwine] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/untwine.dir/all] Error 2
make: *** [Makefile:130: all] Error 2_**

OS:
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

I installed padal and python-pdal via conda:
python-pdal               version 3.1.2 
pdal                             version 2.4.2  

I check the libpda_base.so, but seems like it points to this lib:
ldd libpdal_base.so | grep curl
        libcurl.so.4 => /home/ubuntu/anaconda3/envs/budjbim2/lib/././libcurl.so.4 (0x00007fc7c693d000)

Any help and suggestion?
Many Thanks!

**Comment by hobu** [comment]
Use the conda-forge compilers package too. The compiler you are using is missing a symbol in its glibcxx.

```
conda install -c conda-forge compilers
```

**Comment by zexhuang** [comment]
Thanks @hobu Howard, for the tips!

I have compiled the untwine binary file, but was not able to execute it in terminal.

Any suggestion?

Thanks!
