### ISSUE TITLE
Windows - Built exe not working

### ISSUE THREAD

**Issue by Pourfex** [hobuinc/untwine#137]
Hello,
I built the .exe on windows using those steps : 
- mkdir build
- cd build
- cmake ..
- Open the sln solution that has been generated
- Generate using visual studio 2019 (Generate -> Generate solution)

It does output me untwine.exe and some other files under the Debug/folder : 
- untwine.exe
- untwine.exp
- untwine.lib
- untwine.pdb

I tried using this in a command line untwine.exe
Got errors that it misses pdal_util.dll and pdalcpp.dll 

I tried to use it in a conda env (using miniconda3 command prompt) - with pdal and compilers inside the environnement used.
It got no erros this time but nothing happens if I try this : untwine.exe --files=.\input\ --output=.\output\ (one las file and one laz file inside input).

Does the build workflow is right ? Did I missed something in the usage in the commande line or anaconda environment ?

**Comment by hobu** [comment]
You have successfully built it. You need to have the `%CONDA_PREFIX%\Library\bin` directory in the path so the DLLs can be found.

Untwine is also installable directly from Conda without having to build it yourself.

Please refrain from using GitHub tickets for support. We are available for hire for support if it is a critical item for you.

**Comment by Pourfex** [comment]
I would need to build an .exe for my workflow working on Windows. 
Is there any way to link libraries than this path ?

For now we're considering untwine for our pipeline (las,ept,e57 -> ept), but we haven't been able to test the .exe version on windows which is required by our use case.

Adding some lines for windows .exe building with the step that I used above and your answer with path will be a great addition to the Readme for someone willing to test untwine.
