### ISSUE TITLE
Segfault Exception: Failure writing to

### ISSUE THREAD

**Issue by Jean-Romain** [hobuinc/untwine#140]
I'm trying to run `untwine` on linux. I compiled the source code. Everything was ok. Now I'm trying the following command. No matter the input file (here `autzen-classified.las`) or output directory it always crashes. Numerous `.bin` file are written in `copc/_tmp` but it never goes til this end.

```bash
untwine --files=autzen-classified.las --output_dir=copc/ --single_file=true --progress_debug=true
# Untwine progress (45% done): Reprocessed voxel 4-7-3-0
# Untwine progress (50% done): Reprocessed voxel 4-8-1-0
# Untwine progress (55% done): Reprocessed voxel 4-4-3-0
# Untwine progress (60% done): Reprocessed voxel 4-2-4-0
# Exception: Failure writing to 'copc/'.
# Exception: Failure writing to 'copc/'.
# Untwine progress (61% done): Sample complete for 3-0-1-0
# Exception: Failure writing to 'copc/'.
# Untwine progress (61% done): Sample complete for 3-0-7-0
# [1]    99963 segmentation fault (core dumped)  /home/jr/Téléchargements/untwine/build/untwine --files=autzen-classified.la

**Comment by abellgithub** [comment]
Since the program generally works, you'll have to provide a bunch more info in order to have this figured out. Is your filesystem full? Could there be some other I/O issue with your system? Can you get a traceback from the core file? Can you describe the system you're using?

**Comment by abellgithub** [comment]
What happens if you leave the trailing '/' on the output directory name?

**Comment by Jean-Romain** [comment]
> What happens if you drop the trailing '/' on the output directory name?

I get pretty much the same but instead of creating `./copc/_tmp` it creates `./copc_tmp/

```bash
untwine --files=autzen-classified.las --output_dir=copc --single_file=true --progress_debug=true
# Untwine progress (45% done): Reprocessed voxel 4-2-4-0
# Untwine progress (50% done): Reprocessed voxel 4-4-3-0
# Untwine progress (55% done): Reprocessed voxel 4-8-1-0
# Untwine progress (60% done): Reprocessed voxel 4-7-3-0
# Exception: Failure writing to 'copc'.
# Exception: Untwine progress (61% done): Sample complete for 3-0-1-0
# Failure writing to 'copc'.
# Exception: Failure writing to 'copc'.
# Untwine progress (61% done): Sample complete for 3-0-7-0
# Exception: Failure writing to 'copc'.
# Untwine progress (62% done): Sample complete for 3-0-0-0
# Exception: Failure writing to 'copc'.
# Untwine progress (62% done): Sample complete for 3-1-0-0
# Exception: Failure writing to 'copc'.
# Untwine progress (63% done): Sample complete for 3-1-1-0
# [1]    108302 segmentation fault (core dumped)  /home/jr/Téléchargements/untwine/build/untwine --files=autzen-classified.la
```

>  Is your filesystem full? 

No my filesystem is not full at all I have 8 Gb of free disk space which is not a lot but should be enough for a 80 Mb file.

> Would there be some other I/O issue with your system

I don't know. I'm in a very regular user folder with no I/O restriction. Many `.bin` files where created until it failed.

> Can you get a traceback from the core file?

No. I can run it with `valgrind` but the report is excessively long with 8,503,837 bytes lost in 83,782 blocks

> Can you describe the system you're using?

Linux Mint 20.3

**Comment by hobu** [comment]
>> Can you get a traceback from the core file?
> No. I can run it with valgrind but the report is excessively long with 8,503,837 bytes lost in 83,782 blocks

Can you make a Dockerfile that replicates your build? We're just guessing otherwise.

**Comment by abellgithub** [comment]
I think this is a file existence issue. I can get a similar failure. The SEGV is a red herring that occurs because things threads are dying unceremoniously. I'll try to harden the file access.

**Comment by Jean-Romain** [comment]
> Can you make a Dockerfile that replicates your build? We're just guessing otherwise.

Sorry I'm not using docker and actually never understood anything about it. So far I found easier to compile everything than trying to grasp anything about how to install and use docker. Sorry for my incapacity to provide a more reproducible example.

**Comment by Jean-Romain** [comment]
It successfully worked with absolute path

```r
untwine --files=/home/jr/Documents/laser/autzen-classified.las --output_dir=/tmp/copc --single_file=true --progress_debug=true 
```

**Comment by m-kuhn** [comment]
For reference, I just got bitten by the same and it was because I ran out of space. Next time someone runs into this `df -h` will show the current usage of file systems, in my case I didn't realize that temporary files were written to a different partition than the source files.

**Comment by abellgithub** [comment]
Now tracked in #145
