### ISSUE TITLE
Untwine writes class flags as extra byte attributes when built with pdal 2.6

### ISSUE THREAD

**Issue by uclaros** [hobuinc/untwine#147]
Using pdal 2.6:
```
$ pdal translate \
https://github.com/qgis/QGIS/raw/master/tests/testdata/point_clouds/copc/extrabytes-dataset.copc.laz \
synthetic.laz \
assign \
--filters.assign.value="Synthetic=1" \
--writers.las.forward=all \
--writers.las.extra_dims=all
```
then using untwine built with pdal 2.6:
```
$ untwine -i synthetic.laz -o synthetic.copc.laz -s
```
The resulting copc file has the unexpected Synthetic, KeyPoint, Withheld and Overlap extra dims, while the previous extra dims (Deviation, Amplitude, Reflectance) are removed.
This can be seen using pdal 2.5:
```
pdal info synthetic.copc.laz --schema
```

**Comment by abellgithub** [comment]
PDAL writes LAS version 1.2 by default. You can change this behavior by using `--writers.las.minor_version`. 1.4 classification and class flags don't fit well into version 1.2 files, so PDAL tries its best, which isn't what you expect.

**Comment by uclaros** [comment]
Sorry, the output file in the first command is not 1.2 but rather 1.4, as I'm passing `--writers.las.forward=all`

**Comment by uclaros** [comment]
Using pdal 2.5:
```
pdal info synthetic.laz --schema
```
This output looks correct: ClassFlags is there, 3 extra dims are there, no Synthetic/Withheld/Keypoint/Overlap attributes.
This leads me to believe the issue is in untwine.

**Comment by abellgithub** [comment]
Can you provide the input `synthetic.laz`?

**Comment by uclaros** [comment]
[synthetic.laz.zip](https://github.com/hobuinc/untwine/files/13501777/synthetic.laz.zip)

**Comment by uclaros** [comment]
> I'm guessing that the change to split class flags into separate dimensions in PDAL 2.6 broke Untwine WRT these fields. I will verify. You might try a version of Untwine linked with PDAL 2.5 to check this and get output that you're expecting.

That's my guess too.
I've already checked, Untwine with pdal 2.5 works as expected on a file like synthetic.laz , either if created with pdal 2.5 (--filters.assign.value="ClassFlags=1") or with pdal 2.6 (--filters.assign.value="Synthetic=1")

**Comment by abellgithub** [comment]
I have not looked, but I expect I know what's up with this. I hope to fix it tomorrow.

**Comment by abellgithub** [comment]
This all makes me sad. I have to make some assumptions to fix this given the PDAL change. It will make Untwine a little slower :(

**Comment by uclaros** [comment]
Isn't the assumption that there is no extra dims named _Synthetic, KeyPoint, Withheld or Overlap_ enough? Such extra dims could break other software and confuse users anyway!
Something in the lines of:
```diff
diff --git a/epf/Epf.cpp b/epf/Epf.cpp
index 53b606a..0485849 100644
--- a/epf/Epf.cpp
+++ b/epf/Epf.cpp
@@ -153,6 +153,12 @@ void Epf::run(ProgressWriter& progress)
     PointLayoutPtr layout(new PointLayout());
     for (const std::string& dimName : allDimNames)
     {
+        if ( dimName == "Overlap" ||
+            dimName == "Withheld" ||
+            dimName == "KeyPoint" ||
+            dimName == "Synthetic" )
+            continue;
+
         Dimension::Type type;
         try
         {
```

**Comment by uclaros** [comment]
We're adding a similar approach to handling ClassFlags in QGIS: https://github.com/qgis/QGIS/pull/55299
Point unpacking is done using lazperf anyway, so the PDAL 2.6 changes should not directly affect QGIS, only through Untwine.

I might be missing something, but the above fix that ignores the 4 'fake' attributes gives a resulting copc that looks correct to me and gets its Synthetic, KeyPoint, Withheld and Overlap attributes correctly read by QGIS.

**Comment by abellgithub** [comment]
Hmm. I'm not sure how that would work but I haven't tried it. If you ignore those dimensions, where is the data for those flags going to come from? Or be stored? The 2.6 PDAL code seems to store the class bits only in those dimensions. There is no `ClassFlags` and the data is also not stored in `Classification`.

I misspoke above when I said that the dimensions need to be addressable. The way things work now, all the dimensions ARE addressable, so that isn't an issue.

I will do some testing and update this ticket.

Thanks for your help.

**Comment by abellgithub** [comment]
I verified that just ignoring the bits fields doesn't work (at least with some input).

**Comment by uclaros** [comment]
Could you elaborate on what does not work? Maybe share the input?
With my crafted data, the above fix seems to give correct results.

**Comment by abellgithub** [comment]
How are you reading that data if you ignore those fields?
[autzen_bits.laz.gz](https://github.com/hobuinc/untwine/files/13572362/autzen_bits.laz.gz)

**Comment by abellgithub** [comment]
@uclaros 

https://github.com/hobuinc/untwine/tree/issue-146-147

You can check this out with 2.6. I still have to do some stuff for backward compatibility.

**Comment by uclaros** [comment]
Done in #148
