### ISSUE TITLE
Untwine changes extra bytes attributes from int to float

### ISSUE THREAD

**Issue by uclaros** [hobuinc/untwine#155]
Given the following sample file from https://github.com/qgis/QGIS/issues/54365
https://github.com/qgis/QGIS/files/12435659/example.zip

```
pdal info --schema example.laz
# Attr0 and Attr1 are _signed_

untwine -i example.laz -o example.copc.laz -s

pdal info --schema example.copc.laz
# Attr0 and Attr1 are now float
```

9fafef09 built with pdal 2.6.0

**Comment by abellgithub** [comment]
They should be doubles. Is this what you're seeing?

**Comment by uclaros** [comment]
Yes. In the input laz file they are unsigned integers. I'd expect them to be the same in the generated copc.

**Comment by abellgithub** [comment]
Right. I just wanted to confirm that you were seeing what I expected given the code.

**Comment by nazarred** [comment]
I have a similar problem. In my LAS file, I have `short` and `unsigned short` extrabytes with a scale factor, after I converted that file to COPC with untwine all extrabytes with scale are converted to doubles.

![image](https://github.com/hobuinc/untwine/assets/34417569/d9cb2079-7708-44a7-896c-47e7a8ce1cae)

I used untwine built from the main branch (255d30b0ca6aec8100405b382f66a42fc4e59e1c)

Attaching the original file and COPC created with untwine.

[test_extra_bytes.zip](https://github.com/hobuinc/untwine/files/14466852/test_extra_bytes.zip)

**Comment by abellgithub** [comment]
@nazarred : Currently Untwine uses PDAL to read data and PDAL does not maintain scale/offset for extra bytes dimensions -- that information is lost. At the time the data is read, it is treated as a double (after scale and offset are applied). There are a few reasons for this, but I don't think it's going to change -- it's been this way for at least a decade.

If you need to maintain scale/offset in extra dimensions when transforming from LAS to COPC and can provide funding, please contact us.

**Comment by aritchie-usgs** [comment]
@abellgithub Is this why QGIS drops my confidence and x,y,z normal fields (stored in extra byte fields) from a laz pointcloud created with Metashape? How much funding would it take for this capability to be added? Sample laz file containing data in user byte fields attached
[lowest_dense_clip.zip](https://github.com/hobuinc/untwine/files/14715280/lowest_dense_clip.zip)

**Comment by abellgithub** [comment]
The normals in your file are scaled extra bytes dimensions. If you're converting this file to COPC with Untwine, those dimensions will be transformed into double-precision values. The confidence value is not scaled. I have no idea why this data is being dropped by QGIS. I would ask the QGIS folks.

``` 
Extra Byte Descriptions
      data type: 1 (unsigned char), name "confidence", description: "confidence values", scale: 1 (not set), offset: 0 (not set)
      data type: 2 (char), name "normal x", description: "X surface normal", scale: 0.00787402, offset: 0 (not set)
      data type: 2 (char), name "normal y", description: "Y surface normal", scale: 0.00787402, offset: 0 (not set)
      data type: 2 (char), name "normal z", description: "Z surface normal", scale: 0.00787402, offset: 0 (not set)
```
