### ISSUE TITLE
Untwine no longer producing ept dataset

### ISSUE THREAD

**Issue by SirBob01** [hobuinc/untwine#160]
Has EPT output been deprecated? It seems to only be producing the COPC single file by default and it's ignoring the CLI flag.

**Comment by abellgithub** [comment]
This is correct. You need to use an older version of the software to get
EPT. Or you can use Entwine.

**Comment by abellgithub** [comment]
Changes made to deal with issues #146 and #147 made maintaining EPT support difficult and we didn't think that there was much demand for EPT output with Untwine. If this is something you'd like to fund, please let us know.
