### ISSUE TITLE
Make single_file the default usage?

### ISSUE THREAD

**Issue by hobu** [hobuinc/untwine#66]
Seems reasonable to me that people will want the single_file COPC output by default.

**Comment by abellgithub** [comment]
This would be an unexpected behavior change. I suppose we could make a different default based on the executable name, but that seems like more trouble than it's worth.

**Comment by connormanning** [comment]
Could switch depending on the `--output` ending in `.laz` or `.copc.laz`.  Hard to envision someone wanting an EPT dataset in `some-directory.copc.laz/`.

**Comment by connormanning** [comment]
Oh or is that what you meant by "executable name".  If so, never mind.

**Comment by uclaros** [comment]
I guess this makes more sense after #148

**Comment by abellgithub** [comment]
I'm tempted to split the project in two -- one for EPT and one for COPC. Not sure how much demand there is for EPT generation with Untwine.

**Comment by hobu** [comment]
> Not sure how much demand there is for EPT generation with Untwine.

Supportive. QGIS was the Untwine EPT impetus and it is doing COPC now. Any others doing huge EPT are doing so with split apart Entwine builds.

**Comment by abellgithub** [comment]
Naming suggestions?

**Comment by hobu** [comment]
> Naming suggestions?

You don't want me naming things. History has proven it.
